name: push on main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: récupérer le code
        uses: actions/checkout@v4
      - name: installation des nodes_modules
        run: npm ci
      - name: run test
        run: npm run test
      - name: run build
        run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: dist
          path: dist

  downloadArtifact:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: dist
          path: dist
      - name: List artifact files
        run: |
            ls dist

